config/routes.rb
Rails.application.routes.draw do
  root 'images#index'
  resources :images do
  	get 'delete'
  end
end

app/models/image.rb
class Image < ActiveRecord::Base
	mount_uploader :asset, ImageUploader
	validates :asset, presence: true

	after_destroy :remove_file_directory

  def remove_file_directory
    path = File.dirname(asset.file.file)
    FileUtils.remove_dir(path, force: false)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  before_action :set_image, only: [:show, :edit, :update, :destroy]

  def index
    @images = Image.all
    unless params[:filtro]
      @images = Image.all
    else
      @images = Image.where("tipo = ?", params[:filtro])
    end
    respond_to do |format|
      format.html do
        if request.xhr?
          render layout: false
        end
      end
    end
  end

  def show
  end

  def new
    @image = Image.new
    respond_to do |format|
      format.html do
        if request.xhr?
          render layout: false
        end
      end
    end
  end

  def edit
    respond_to do |format|
      format.html do
        if request.xhr?
          render layout: false
        end
      end
    end
  end

  def create

    @image = Image.new(image_params)

    set_tipo @image

    respond_to do |format|
      if @image.save
        format.html do
          # a verificação do parâmetro adicionado na requisição ajax garante o retorno correto no ie explorer
          if request.xhr? || params[:xhr]
             render plain: "Arquivo criado com sucesso"
          else
            redirect_to images_path, notice: 'Image was successfully created.'
          end
        end
        format.json { render :show, status: :created, location: @image }
      else
        format.html do
          if request.xhr?
            render partial: "alert"
          else
            flash[:error] = "Erro ao criar o arquivo"
            flash.discard :error
            render :new
          end
        end
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    set_tipo @image
    respond_to do |format|
      if @image.update(image_params)
        format.html do
          if request.xhr?
             render plain: "Arquivo editado com sucesso"
          else
            redirect_to images_path, notice: 'Arquivo editado com sucesso.'
          end
        end
        format.json { render :show, status: :created, location: @image }
      else
        format.html do
          if request.xhr?
            render partial: "alert"
          else
            flash[:error] = "Erro ao criar o arquivo"
            flash.discard :error
            render :edit
          end
        end
        format.json { render json: @image.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @image.destroy
    respond_to do |format|
      format.html { redirect_to images_url, notice: 'Image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete
    @image = Image.find(params[:image_id])
    @image.destroy
    respond_to do |format|
      format.html do
        if request.xhr?
          render plain: "Ok"
        else
          flash[:notice] = 'Image was successfully destroyed.'
          flash.discard :notice
          redirect_to images_url
        end
      end
    end
  end

  private
    def set_image
      @image = Image.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:asset, :title, :description)
    end

    def set_tipo img
      tipo = params[:image][:asset].try(:content_type)
      unless tipo.nil?
        if  tipo.include? "image"
          img.tipo = "images"
        elsif  tipo.include? "video"
          img.tipo = "videos"
        else
          img.tipo = "files"
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_alert.html.erb
<!-- 
<a href="" class="uk-alert-close uk-close"></a>
-->
<% if @image.errors.any? %>
  <%= javascript_tag do -%>
    $('#debug').removeClass('uk-hidden');
  <%- end -%>
  <strong><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</strong>
  <p id="error_explanation">
    <ul style="list-style-type: disc;">
    <% @image.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </p>
<% end %>
<p class="msg"></p>

app/views/images/_form.html.erb
<div id="debug" class="uk-alert uk-hidden" data-uk-alert="">
  <%#= render 'alert' %>
</div>

<div id="progressbar" class="uk-progress uk-hidden">
    <div class="uk-progress-bar" style="width: 0%;"></div>
</div>

<%= form_for(@image, html: {name: "uploader", class: "uk-form uk-form-stacked"}) do |f| %>


  <div class="uk-form-row">
    <div class="uk-form-file">
        <button class="uk-button"><%= params[:action] == 'new' ? 'Select' : 'Alterar arquivo' %></button>
        <%= f.file_field :asset, id: 'upload-select1' %>
    </div>
    <span class="filename"></span>                           
    <span class="selecione">selecione um arquivo para envio.</span>
  </div>
  <div class="uk-form-row">
    <%= f.label :title, 'Título', class: 'uk-form-label' %>
    <div class="uk-form-controls">
        <%= f.text_field :title, class: 'uk-width-1-1', placeholder: 'Informe o título' %>
    </div>
  </div>

  <div class="uk-form-row">
      <%= f.label :description, 'Descrição', class: 'uk-form-label' %>
      <div class="uk-form-controls">
          <%= f.text_area :description, cols: 100, rows: 9, class: 'uk-width-1-1', placeholder: 'Adicione uma descrição ao arquivo' %>
      </div>
  </div>
<!--
  <div class="field">
    <%#= f.label :tipo %><br>
    <%#= f.select :tipo, [["imagem","imagem"],["video","video"]] %>
  </div>
-->
  <div class="uk-form-row">
      <div class="uk-form-controls">
          <%= f.button class: 'uk-button uk-button-primary' %>
      </div>
  </div>
<% end %>

app/views/images/_new.html.erb
<div class="uk-1-1">
	<div class="uk-panel uk-panel-header uk-panel-box uk-text-left">
	  <h3 class="uk-panel-title">Envio de arquivo</h3>
		<%= render 'form' %>
	</div>
</div>
<a href="#" class="closemodal">X FECHAR</a>

app/views/images/edit.html.erb
<div class="<%= request.xhr? ? 'uk-width-1-1' : 'uk-width-8-10 uk-push-1-10' %>">
	<div class="uk-panel uk-panel-header uk-panel-box uk-text-left">
	  <h3 class="uk-panel-title">Alterar arquivo ou imagem</h3>
	  <% if @image.tipo == 'images' %>
		  <div class="uk-panel uk-panel-box uk-text-center uk-width-2-3 uk-align-center">
		    <div class="uk-panel-teaser">
		        <%= image_tag @image.asset.thumb %>
		    </div>
		    <p><%= File.basename(@image.asset.path) %></p>
			</div>	    
	  <% end %>  

	  <% if flash[:error] %>
		  <div id="debug" class="uk-alert uk-alert-danger" data-uk-alert="">
		    <strong><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</strong>
			  <p id="error_explanation">
			    <ul style="list-style-type: disc;">
			    <% @image.errors.full_messages.each do |message| %>
			      <li><%= message %></li>
			    <% end %>
			    </ul>
			  </p>
			 </div>
		<% end %>
		<%= render 'form' %>
	</div>
</div>
<% if request.xhr? %>
	<a href="#" class="closemodal">X FECHAR</a>
<% end -%>
<%#= link_to 'Show', @image %>
<%#= link_to 'Back', images_path %>

app/views/images/index.html.erb
 <% @images.each do |image| %>
  <li class="file j_<%= image.id %>">
    <div class="li-box">
      <% if image.tipo == "images" %>
        <img src="<%= image.asset.thumb %>" alt="Baixar arquivo" title="Baixar Arquivo" width="273" height="120" />
      <% elsif image.tipo == "videos" %>
        <img src="<%= asset_path 'videothumb.jpg' %>" alt="Baixar arquivo" title="Baixar Arquivo" width="273" height="120" />
      <% else %>
        <img src="<%= asset_path 'filethumb.jpg' %>" alt="Baixar arquivo" title="Baixar Arquivo" width="273" height="120" />
      <% end %>
        <h2><%= image.title %></h2>
        <p class="desc"><%= image.description %></p>
        <p class="data"><%= image.created_at.localtime.strftime("Enviado em: %d/%m/%Y às %I:%M%p") %></p>
        <p><a class="uk-button" href="<%= image.asset %>" 
          <%= raw(
              if image.tipo == "images"
                'rel="shadowbox"'
              elsif image.tipo == "videos"
                # https://qianflora.wordpress.com/2014/01/15/play-youtube-video-with-shadowbox-on-iphone-and-ipad/
                'rel="shadowbox;width=853;height=480;player=iframe"'
              end
            )
          -%> >Veja isto!</a></p>
        <div class="manage">
          <a class="actionedit <%= image.id %>" href="/images/<%= image.id %>/edit"><img src="<%= asset_path('edit.png') %>" alt="" title="" /></a>
          <%= link_to image_delete_path(image), class: "actiondelete #{image.id}" do %>
            <img src="<%= asset_path('delete.png') %>" alt="" title="" />
          <% end -%>
        </div>
      </div>
  </li>
<% end %>

app/views/images/new.html.erb
<div class="<%= request.xhr? ? 'uk-width-1-1' : 'uk-width-8-10 uk-push-1-10' %>">
	<div class="uk-panel uk-panel-header uk-panel-box uk-text-left">
	  <h3 class="uk-panel-title">Envio de arquivo</h3>
	  <% if flash[:error] %>
		  <div id="debug" class="uk-alert uk-alert-danger" data-uk-alert="">
		    <strong><%= pluralize(@image.errors.count, "error") %> prohibited this image from being saved:</strong>
			  <p id="error_explanation">
			    <ul style="list-style-type: disc;">
			    <% @image.errors.full_messages.each do |message| %>
			      <li><%= message %></li>
			    <% end %>
			    </ul>
			  </p>
			 </div>
		<% end %>
		<%= render 'form' %>
	</div>
</div>
<% if request.xhr? %>
	<a href="#" class="closemodal">X FECHAR</a>
<% end -%>

app/views/images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Asset:</strong>
  <%= @image.asset %>
</p>

<p>
  <strong>Title:</strong>
  <%= @image.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @image.description %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @image.tipo %>
</p>

<%= link_to 'Edit', edit_image_path(@image) %> |
<%= link_to 'Back', images_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsUploader</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<!--[if lte IE 9]>
<body class="ie">
<![endif]-->
<!--[if !IE]> -->
<body>
<!-- <![endif]-->

<div class="uk-container uk-container-center uk-margin-top container-shadow">

  <div class="uk-grid" data-uk-grid-margin="">
      <div class="uk-width-1-1 uk-text-center">
        <img class="logo" src="<%= asset_path('logohub.png') -%>" alt="Sistema de arquivos" title="Sistema de arquivos" />
      </div>
  </div>

  <nav class="uk-navbar uk-margin-bottom-remove">

      <ul class="menu uk-navbar-nav uk-hidden-small ">
          <li>
              <%= link_to "Cadastrar mais", new_image_path, class: 'cadastrar_imagem' %>
          </li>
          <li>
              <%= link_to "Ver tudo", images_path, class: 'ver_tudo' %>
          </li>
          <li>
              <%= link_to "Ver arquivos", images_path(filtro: 'files'), class: 'ver_arquivos' %>
          </li>
          <li>
              <%= link_to "Ver imagens", images_path(filtro: 'images'), class: 'ver_imagens' %>
          </li>
          <li>
              <%= link_to "Ver vídeos", images_path(filtro: 'videos'), class: 'ver_videos' %>
          </li>
      </ul>
      <a href="#offcanvas" class="uk-navbar-toggle uk-visible-small" data-uk-offcanvas=""></a>
  </nav>

  <div class="uk-grid" data-uk-grid-margin>
    <div class="uk-width-medium-1-1 uk-text-center">
      <div class="galeria">
        <div class="loading"><img src="<%= asset_path('load.gif') -%>" alt="Carregando..." title="Carregando..." />&nbsp;&nbsp;Aguarde, carregando informações!</div>
        <% if flash[:notice] %>
          <div class="uk-alert" data-uk-alert="">
              <!-- <a href="" class="uk-alert-close uk-close"></a> -->
              <p><%= flash[:notice] %></p>
          </div>
        <% end %> 
          <ul class="uk-grid uk-grid-width-1-2 uk-grid-width-large-1-3 lista" data-uk-grid-margin>

  					<%= yield %>

          </ul>
        </div>
    </div>
  </div>  
</div> <!-- fim container -->

<div id="offcanvas" class="uk-offcanvas">
  <div class="uk-offcanvas-bar">
    <ul class="uk-nav uk-nav-offcanvas">
      <li>
          <a href="layouts_frontpage.html">Frontpage</a>
      </li>
         <li>
          <a href="layouts_portfolio.html">Portfolio</a>
      </li>
      <li>
          <a href="layouts_blog.html">Blog</a>
      </li>
         <li>
          <a href="layouts_documentation.html">Documentation</a>
      </li>
      <li class="uk-active">
          <a href="layouts_contact.html">Contact</a>
      </li>
      <li>
          <a href="layouts_login.html">Login</a>
      </li>
      </ul>
    </div>
</div>   
<div class="modal"></div>
</body>
</html>